import { describe, expect, it } from 'vitest'
import { LiveDeckTracker, parseDeckScreen, identifyDeckCard, type DeckScreen, type DeckTextLine } from '../main/deck/live-deck'
import type { CardRow } from '../shared/state'
const names = ['Campus Crier', 'Predictive Preparations', 'Teyo, Lightshield Expert', 'Germinate Recruits', 'Koth of the Homestead', 'Yuriko, Blade of the Mighty', 'Yuriko, Hope from the Shadows', 'Plains', 'Island']
const pool = names.map(name => ({ name } as CardRow))
const line = (text: string, x: number, y: number, width = .14): DeckTextLine => ({ text, x, y, width, height: .02, confidence: 1 })
function screen(total: number, entries: Array<[string, number]>, at = 1000): DeckScreen {
  return { at, width: 1280, height: 748, status: 'ok', lines: [line(`${total}/40 Cards`, .83, .16), ...entries.flatMap(([name, count], i) => [line(`${count}x`, .79, .22 + i * .043, .02), line(name, .816, .22 + i * .043)])] }
}
function stable(t: LiveDeckTracker, s: DeckScreen) { t.observe(s); return t.observe({ ...s, at: s.at + 500 }) }
function tracker() { const t = new LiveDeckTracker(); t.setPool('pool', pool); return t }

describe('live deck observation', () => {
  it('reads separate quantity/name boxes, truncated titles, and automatic lands', () => {
    const parsed = parseDeckScreen(screen(23, [['Campus Crier', 1], ['Predictive Preparations', 1], ['Teyo, Lightshield Expert', 1], ['Germinate Recruits', 1], ['Koth of the Homestead', 1], ['Yuriko, Blade of the Mi...', 1], ['Plains', 17]]), names)
    expect(parsed.total).toBe(23)
    expect(parsed.counts).toEqual({ 'Campus Crier': 1, 'Predictive Preparations': 1, 'Teyo, Lightshield Expert': 1, 'Germinate Recruits': 1, 'Koth of the Homestead': 1, 'Yuriko, Blade of the Mighty': 1, Plains: 17 })
    expect(identifyDeckCard('Yuriko', names)).toBeNull()
  })
  it('accepts detached digits only in quantity boxes and reads two-digit lands with a border glyph', () => {
    const observed = screen(12, [])
    observed.lines.push(line('1', .791, .22, .007), line('x', .800, .22, .006), line('Campus Crier', .816, .22),
      line('1', .791, .263, .007), line('Predictive Preparations', .816, .263),
      line('10x(', .788, .306, .024), line('Plains', .816, .306))
    expect(parseDeckScreen(observed, names).counts).toEqual({ 'Campus Crier': 1, 'Predictive Preparations': 1, Plains: 10 })
    const unsafe = screen(1, [])
    unsafe.lines.push(line('1', .75, .22, .01), line('Campus Crier', .816, .22), line('2', .969, .22, .01))
    expect(parseDeckScreen(unsafe, names).counts).toEqual({})
  })
  it('repairs one basic-land glyph only when five or more letters identify a unique card', () => {
    const basicNames = [...names, 'Forest', 'Swamp', 'Mountain']
    expect(identifyDeckCard('Islana', basicNames)).toBe('Island')
    expect(identifyDeckCard('Fores', basicNames)).toBe('Forest')
    expect(identifyDeckCard('Mountai', basicNames)).toBe('Mountain')
    expect(identifyDeckCard('land', basicNames)).toBeNull()
    expect(identifyDeckCard('Islxnz', basicNames)).toBeNull()
    expect(identifyDeckCard('Islan', [...basicNames, 'Islam'])).toBeNull()
    const parsed = parseDeckScreen(screen(16, [['Plains', 7], ['Islana', 9]]), basicNames)
    expect(parsed.counts).toEqual({ Plains: 7, Island: 9 })
  })
  it('requires two stable reads and observes additions and removals without manual checks', () => {
    const t = tracker()
    expect(t.observe(screen(18, [['Campus Crier', 1], ['Plains', 17]])).status).toBe('scanning')
    expect(stable(t, screen(18, [['Campus Crier', 1], ['Plains', 17]])).counts).toEqual({ 'Campus Crier': 1, Plains: 17 })
    expect(stable(t, screen(19, [['Campus Crier', 2], ['Plains', 17]], 3000)).counts['Campus Crier']).toBe(2)
    expect(stable(t, screen(17, [['Plains', 17]], 5000)).counts['Campus Crier']).toBeUndefined()
  })
  it('confirms rows across alternating OCR omissions without waiting for identical whole lists', () => {
    const t = tracker()
    expect(t.observe(screen(19, [['Campus Crier', 1], ['Plains', 17]], 1000)).status).toBe('scanning')
    t.observe(screen(19, [['Predictive Preparations', 1], ['Plains', 17]], 2000))
    const partial = t.observe(screen(19, [['Campus Crier', 1], ['Predictive Preparations', 1]], 3000))
    expect(partial.status).toBe('live')
    expect(partial.counts).toEqual({ 'Campus Crier': 1, 'Predictive Preparations': 1, Plains: 17 })
  })
  it('does not apply a transient quantity misread or certify it from older complete scan evidence', () => {
    const t = tracker()
    stable(t, screen(19, [['Campus Crier', 1], ['Predictive Preparations', 1], ['Plains', 17]]))
    const transient = t.observe(screen(19, [['Campus Crier', 3], ['Predictive Preparations', 1], ['Plains', 17]], 2000))
    expect(transient.status).toBe('uncertain')
    expect(transient.counts['Campus Crier']).toBe(1)
    const missedNext = t.observe(screen(19, [['Predictive Preparations', 1], ['Plains', 17]], 3000))
    expect(missedNext.status).toBe('uncertain')
    expect(missedNext.counts['Campus Crier']).toBe(1)
    const recovered = stable(t, screen(19, [['Campus Crier', 1], ['Predictive Preparations', 1], ['Plains', 17]], 4000))
    expect(recovered.status).toBe('live')
    expect(recovered.counts['Campus Crier']).toBe(1)
  })
  it('preserves hidden rows and verifies a removed last copy with both click and total', () => {
    const t = tracker()
    stable(t, screen(19, [['Campus Crier', 1], ['Teyo, Lightshield Expert', 1], ['Plains', 17]]))
    t.noteClick(.85, .23, 1600)
    const state = stable(t, screen(18, [['Teyo, Lightshield Expert', 1]], 2000))
    expect(state.status).toBe('uncertain')
    expect(state.counts).toEqual({ 'Teyo, Lightshield Expert': 1, Plains: 17 })
    expect(stable(t, screen(18, [['Plains', 17]], 3000)).status).toBe('live')
  })
  it('can recover a partial deck by scrolling, without treating unseen cards as cuts', () => {
    const t = tracker()
    expect(stable(t, screen(19, [['Campus Crier', 1], ['Teyo, Lightshield Expert', 1]])).status).toBe('uncertain')
    const state = stable(t, screen(19, [['Plains', 17]], 3000))
    expect(state.status).toBe('live')
    expect(state.counts).toEqual({ 'Campus Crier': 1, 'Teyo, Lightshield Expert': 1, Plains: 17 })
  })
  it('does not guess quantities or erase the deck when a menu obscures it', () => {
    const t = tracker(); stable(t, screen(18, [['Campus Crier', 1], ['Plains', 17]]))
    const obscured = { ...screen(0, []), lines: [line('Options', .4, .3)] }
    const state = t.observe(obscured)
    expect(state.status).toBe('uncertain')
    expect(state.counts.Plains).toBe(17)
    expect(parseDeckScreen({ ...screen(1, []), lines: [line('1/40 Cards', .83, .16), line('Campus Crier', .82, .24)] }, names).counts).toEqual({})
  })
  it('keeps permission and saved-deck states honest', () => {
    const t = tracker(); t.saved({ Plains: 17, 'Campus Crier': 1 })
    expect(t.current.status).toBe('saved')
    expect(t.observe({ at: 3000, width: 1280, height: 748, status: 'unavailable', reason: 'permission', lines: [] }).status).toBe('permission')
    expect(t.current.counts.Plains).toBe(17)
  })
  it.each(['background', 'no-header', 'scene-leave'])('requires fresh row coverage after %s even when the reopened deck has the same total', interruption => {
    const t = tracker()
    stable(t, screen(19, [['Campus Crier', 1], ['Teyo, Lightshield Expert', 1], ['Plains', 17]]))
    if (interruption === 'background') t.observe({ at: 1600, width: 1280, height: 748, status: 'unavailable', reason: 'background', lines: [] })
    else if (interruption === 'no-header') t.observe({ ...screen(0, [], 1600), lines: [line('Options', .4, .3)] })
    else t.invalidate()
    expect(t.current.status).toBe('uncertain')
    expect(t.current.counts['Campus Crier']).toBe(1)
    // The old row must no longer be a click target; the newly opened deck has
    // replaced Campus Crier with Predictive Preparations outside the viewport.
    t.noteClick(.85, .23, 1700)
    const partial = stable(t, screen(19, [['Teyo, Lightshield Expert', 1]], 2000))
    expect(partial.status).toBe('uncertain')
    expect(partial.counts.Plains).toBe(17)
    const complete = stable(t, screen(19, [['Predictive Preparations', 1], ['Plains', 17]], 3000))
    expect(complete.status).toBe('live')
    expect(complete.counts).toEqual({ 'Teyo, Lightshield Expert': 1, 'Predictive Preparations': 1, Plains: 17 })
  })
  it('preserves fresh scrolling evidence when the pool page arrow or gutter is clicked', () => {
    const t = tracker()
    expect(stable(t, screen(19, [['Campus Crier', 1]])).status).toBe('uncertain')
    t.noteClick(.767, .50, 1600)
    t.noteClick(.02, .50, 1650)
    const state = stable(t, screen(19, [['Teyo, Lightshield Expert', 1], ['Plains', 17]], 2000))
    expect(state.status).toBe('live')
    expect(state.counts).toEqual({ 'Campus Crier': 1, 'Teyo, Lightshield Expert': 1, Plains: 17 })
  })
  it('does not publish guessed extra copies when rapid pool clicks outrun the rendered title image', () => {
    const t = tracker()
    // Two copies exist, but only one click actually adds a card before the pool
    // rearranges. The second click was attributed using the old title image.
    t.setPool('rapid', [...pool, { name: 'Predictive Preparations' } as CardRow])
    t.saved({ 'Campus Crier': 1, Plains: 17 }, 500)
    const before = screen(18, [['Plains', 17]])
    before.lines.push(line('Predictive Preparations', .05, .25))
    stable(t, before)
    t.noteClick(.10, .35, 1600)
    t.noteClick(.10, .35, 1650)
    const uncertain = stable(t, screen(19, [['Plains', 17]], 2000))
    expect(uncertain.status).toBe('uncertain')
    expect(uncertain.counts['Predictive Preparations']).toBeUndefined()
    expect(uncertain.counts['Campus Crier']).toBe(1)
    expect(uncertain.counts.Plains).toBe(17)
    // Repeating a partial read cannot resurrect the rejected click delta.
    expect(stable(t, screen(19, [['Plains', 17]], 3000)).counts['Predictive Preparations']).toBeUndefined()
    const resynced = stable(t, screen(19, [['Campus Crier', 1], ['Predictive Preparations', 1]], 4000))
    expect(resynced.status).toBe('live')
    expect(resynced.counts).toEqual({ 'Campus Crier': 1, 'Predictive Preparations': 1, Plains: 17 })
  })
  it('rejects a hidden inferred copy beyond the pool even if its total would reconcile', () => {
    const t = tracker()
    t.saved({ 'Campus Crier': 1, Plains: 17 }, 500)
    const before = screen(18, [['Plains', 17]])
    before.lines.push(line('Campus Crier', .05, .25))
    stable(t, before)
    t.noteClick(.10, .35, 1600)
    const state = stable(t, screen(19, [['Plains', 17]], 2000))
    expect(state.status).toBe('uncertain')
    expect(state.counts['Campus Crier']).toBe(1)
    expect(stable(t, screen(19, [['Plains', 17]], 3000)).status).toBe('uncertain')
  })
  it('counts actual duplicate pool copies when confirming a hidden addition', () => {
    const t = tracker()
    t.setPool('duplicates', [...pool, { name: 'Campus Crier' } as CardRow])
    t.saved({ 'Campus Crier': 1, Plains: 17 }, 500)
    const before = screen(18, [['Plains', 17]])
    before.lines.push(line('Campus Crier', .05, .25))
    stable(t, before)
    t.noteClick(.10, .35, 1600)
    const state = stable(t, screen(19, [['Plains', 17]], 2000))
    expect(state.status).toBe('live')
    expect(state.counts).toEqual({ 'Campus Crier': 2, Plains: 17 })
  })
  it('cannot certify a same-total hidden replacement after an unattributed card click', () => {
    const t = tracker()
    t.saved({ 'Campus Crier': 1, Plains: 17 }, 500)
    stable(t, screen(18, [['Plains', 17]]))
    t.noteClick(.50, .50, 1600)
    const partial = stable(t, screen(18, [['Plains', 17]], 2000))
    expect(partial.status).toBe('uncertain')
    const fresh = stable(t, screen(18, [['Predictive Preparations', 1]], 3000))
    expect(fresh.status).toBe('live')
    expect(fresh.counts).toEqual({ 'Predictive Preparations': 1, Plains: 17 })
  })
  it('requires fresh basics after Arena redistributes an unchanged 17-land total offscreen', () => {
    const t = tracker()
    stable(t, screen(18, [['Campus Crier', 1], ['Plains', 9], ['Island', 8]]))
    // An unrecognized pool click adds a spell. Arena moves one automatic basic
    // from Plains to Island, so the old mana base would still sum to the header.
    t.noteClick(.50, .50, 1600)
    const partial = stable(t, screen(19, [['Campus Crier', 1], ['Predictive Preparations', 1]], 2000))
    expect(partial.status).toBe('uncertain')
    expect(partial.counts.Plains).toBe(9)
    expect(partial.counts.Island).toBe(8)
    expect(partial.message).toContain('lands')
    expect(stable(t, screen(19, [['Plains', 8]], 3000)).status).toBe('uncertain')
    const reconciled = stable(t, screen(19, [['Island', 9]], 4000))
    expect(reconciled.status).toBe('live')
    expect(reconciled.counts).toEqual({ 'Campus Crier': 1, 'Predictive Preparations': 1, Plains: 8, Island: 9 })
  })
  it('also checks hidden lands after an identified removal whose total otherwise reconciles', () => {
    const t = tracker()
    stable(t, screen(19, [['Campus Crier', 1], ['Predictive Preparations', 1], ['Plains', 9], ['Island', 8]]))
    t.noteClick(.85, .23, 1600)
    const partial = stable(t, screen(18, [['Predictive Preparations', 1]], 2000))
    expect(partial.status).toBe('uncertain')
    expect(partial.counts['Campus Crier']).toBeUndefined()
    expect(partial.counts['Predictive Preparations']).toBe(1)
    const reconciled = stable(t, screen(18, [['Plains', 8], ['Island', 9]], 3000))
    expect(reconciled.status).toBe('live')
    expect(reconciled.counts).toEqual({ 'Predictive Preparations': 1, Plains: 8, Island: 9 })
  })
})
