/**
 * Arena's own answer to "what card is this grpId, and where does Arena draw it?"
 *
 * The set bundles derive grpId -> card from Scryfall's `arena_id`, which is a
 * third-party mapping onto Arena's ids rather than Arena's own table. Measured
 * against Arena's database on 2026-09-08, that mapping had eight basic-land ids
 * pointing at the wrong land (grpId 87455 is an Island; we called it a Plains)
 * and 30 draftable ids it did not know at all.
 *
 * Neither failure is cosmetic. The badge grid is matched to cards positionally
 * through `shared/display-order.ts`, so one wrong or missing identity reorders
 * every card after it and the automated picker clicks the wrong card.
 *
 * `arena-cards.json` is generated by `scripts/build_arena_mapping.py
 * --emit-app-cards` and ships inside the app, so a machine without Arena
 * installed still gets correct identity. `ArenaCardDb` (arena-card-db.ts) is
 * the live fallback for ids newer than the shipped file.
 */

import { crossSourceTitleKey as orderKey } from '../../shared/cards'
import { existsSync, readFileSync } from 'fs'
import { join } from 'path'

/** Arena's three sort keys: rarity tier, colour slot, normalised title. */
export type ArenaOrder = readonly [number, number, string]

export interface ArenaCards {
  /** grpId -> card name, verbatim from Arena. */
  name(grpId: number): string | undefined
  /**
   * grpId -> Arena's sort keys.
   *
   * Keyed by grpId, not by name: the keys are a property of the PRINTING. Keyed
   * by name, LCI's Sorcerous Spyglass (uncommon) inherited XLN's rare tier and
   * sorted into the wrong block, shifting every badge after it.
   */
  order(grpId: number, name?: string, rarity?: string): ArenaOrder | undefined
  /** Every (grpId, name) pair, for correcting a set bundle. */
  entries(): IterableIterator<[number, string]>
  readonly size: number
}

const EMPTY: ArenaCards = {
  name: () => undefined,
  order: () => undefined,
  entries: function* () {},
  size: 0
}


interface RawArenaCards {
  ids?: Record<string, string>
  /** grpId -> [Order_MythicToCommon, Order_ColorOrder, Order_Title]. */
  order?: Record<string, [number, number, string]>
  /** Card name -> the primary printing's keys, for printings that carry none. */
  orderByName?: Record<string, [number, number, string]>
}

const cache = new Map<string, ArenaCards>()

/** Load `<bundleRoot>/arena-cards.json`; absent or malformed yields an empty table. */
export function loadArenaCards(bundleRoot: string): ArenaCards {
  const cached = cache.get(bundleRoot)
  if (cached) return cached

  const path = join(bundleRoot, 'arena-cards.json')
  let table = EMPTY
  if (existsSync(path)) {
    try {
      const raw = JSON.parse(readFileSync(path, 'utf-8')) as RawArenaCards
      const ids = new Map<number, string>()
      for (const [key, value] of Object.entries(raw.ids ?? {})) {
        const grpId = Number(key)
        if (Number.isFinite(grpId) && typeof value === 'string' && value) ids.set(grpId, value)
      }
      const orders = new Map<number, ArenaOrder>()
      for (const [key, value] of Object.entries(raw.order ?? {})) {
        const grpId = Number(key)
        // Both ranks must be real numbers. A [null, null, title] tuple used to
        // pass the length check, and `null - 4` is -4, so such a card sorted
        // ahead of every mythic in the pack.
        if (!Number.isFinite(grpId) || !Array.isArray(value) || value.length !== 3) continue
        if (!Number.isFinite(value[0]) || !Number.isFinite(value[1]) || typeof value[2] !== 'string') continue
        orders.set(grpId, value as ArenaOrder)
      }
      const byName = new Map<string, ArenaOrder>()
      for (const [name, value] of Object.entries(raw.orderByName ?? {})) {
        if (!Array.isArray(value) || value.length !== 3) continue
        if (!Number.isFinite(value[0]) || !Number.isFinite(value[1]) || typeof value[2] !== 'string') continue
        const bar = name.lastIndexOf('|')
        const key = bar === -1 ? orderKey(name) : `${orderKey(name.slice(0, bar))}|${name.slice(bar + 1)}`
        byName.set(key, value as ArenaOrder)
      }
      table = {
        name: g => ids.get(g),
        // The printing's own keys, then any printing of the same card. Alchemy
        // and other non-primary rows often carry no keys at all, and one such
        // card drops the whole pack to the reconstruction.
        order: (g, n, r) => orders.get(g) ?? (n === undefined ? undefined : nameOrder(byName, n, r)),
        entries: () => ids.entries(),
        size: ids.size
      }
      if (ids.size === 0) console.warn('[ArenaCards] arena-cards.json parsed but held no ids')
    } catch (error) {
      // Never fail a draft over a corrupt correction file; the bundle's own
      // Scryfall-derived identity still works, just with the known defects.
      console.error('[ArenaCards] failed to read arena-cards.json:', error)
    }
  }
  cache.set(bundleRoot, table)
  return table
}

/**
 * Look up a name's keys, trying the front face when the whole name misses.
 *
 * Our bundles name a modal or split card by both faces
 * ("Bofur, Reliable Guardian // Concerted Care") where Arena stores only the
 * front. Seventeen HOB cards missed for exactly that reason, and every HOB pack
 * containing one lost Arena's ordering entirely.
 */
function nameOrder(byName: Map<string, ArenaOrder>, name: string, rarity?: string): ArenaOrder | undefined {
  // Rarity first, so a borrowed tier at least matches this card's own rarity.
  // Without it, 202 cards took a tier that contradicted their rarity — a mythic
  // filed as an uncommon sorts into the wrong block, which is the very bug the
  // grpId keying was introduced to fix.
  const names = [name]
  const front = name.split(/\s*\/\/+\s*/)[0]
  if (front && front !== name) names.push(front)
  const tiers = rarity ? [RARITY_CODE[rarity.toLowerCase()], undefined] : [undefined]
  for (const tier of tiers) {
    for (const n of names) {
      const hit = byName.get(tier === undefined ? orderKey(n) : `${orderKey(n)}|${tier}`)
      if (hit) return hit
    }
  }
  return undefined
}

/** Arena's Rarity enum, as build_arena_mapping.py writes the fallback keys. */
const RARITY_CODE: Readonly<Record<string, number>> = {
  token: 0, land: 1, basic: 1, common: 2, uncommon: 3, rare: 4, mythic: 5
}

/** Test seam: drop the memoised table so a regenerated file is picked up. */
export function clearArenaCardsCache(): void {
  cache.clear()
}
