/**
 * Arena's own answer to "what card is this grpId, and where does Arena draw it?"
 *
 * The set bundles derive grpId -> card from Scryfall's `arena_id`, which is a
 * third-party mapping onto Arena's ids rather than Arena's own table. Measured
 * against Arena's database on 2026-09-08, that mapping had eight basic-land ids
 * pointing at the wrong land (grpId 87455 is an Island; we called it a Plains)
 * and 30 draftable ids it did not know at all.
 *
 * Neither failure is cosmetic. The badge grid is matched to cards positionally
 * through `shared/display-order.ts`, so one wrong or missing identity reorders
 * every card after it and the automated picker clicks the wrong card.
 *
 * `arena-cards.json` is generated by `scripts/build_arena_mapping.py
 * --emit-app-cards` and ships inside the app, so a machine without Arena
 * installed still gets correct identity. `ArenaCardDb` (arena-card-db.ts) is
 * the live fallback for ids newer than the shipped file.
 */

import { existsSync, readFileSync } from 'fs'
import { join } from 'path'

/** Arena's three sort keys: rarity tier, colour slot, normalised title. */
export type ArenaOrder = readonly [number, number, string]

export interface ArenaCards {
  /** grpId -> card name, verbatim from Arena. */
  name(grpId: number): string | undefined
  /** Card name -> Arena's sort keys. */
  order(name: string): ArenaOrder | undefined
  /** Every (grpId, name) pair, for correcting a set bundle. */
  entries(): IterableIterator<[number, string]>
  readonly size: number
}

const EMPTY: ArenaCards = {
  name: () => undefined,
  order: () => undefined,
  entries: function* () {},
  size: 0
}

/**
 * Bridge the naming conventions between our bundles and Arena for the sole
 * purpose of finding a card's sort keys.
 *
 * The same physical card is spelled differently on each side: Scryfall prefixes
 * Alchemy rebalances with "A-", writes split cards with "//" where Arena writes
 * "///", and names a meld card from the other face. Without this, a pack
 * holding any of those loses Arena's ordering entirely, because the keys are
 * all-or-nothing per pack.
 */
function orderKey(name: string): string {
  return name
    .toLowerCase()
    .replace(/^a-/, '')
    .replace(/\/{2,}/g, '/')
    .replace(/[^a-z0-9/]/g, '')
}

interface RawArenaCards {
  ids?: Record<string, string>
  order?: Record<string, [number, number, string]>
}

const cache = new Map<string, ArenaCards>()

/** Load `<bundleRoot>/arena-cards.json`; absent or malformed yields an empty table. */
export function loadArenaCards(bundleRoot: string): ArenaCards {
  const cached = cache.get(bundleRoot)
  if (cached) return cached

  const path = join(bundleRoot, 'arena-cards.json')
  let table = EMPTY
  if (existsSync(path)) {
    try {
      const raw = JSON.parse(readFileSync(path, 'utf-8')) as RawArenaCards
      const ids = new Map<number, string>()
      for (const [key, value] of Object.entries(raw.ids ?? {})) {
        const grpId = Number(key)
        if (Number.isFinite(grpId) && typeof value === 'string' && value) ids.set(grpId, value)
      }
      const orders = new Map<string, ArenaOrder>()
      for (const [name, value] of Object.entries(raw.order ?? {})) {
        if (Array.isArray(value) && value.length === 3) orders.set(orderKey(name), value as ArenaOrder)
      }
      table = {
        name: g => ids.get(g),
        order: n => orders.get(orderKey(n)),
        entries: () => ids.entries(),
        size: ids.size
      }
      if (ids.size === 0) console.warn('[ArenaCards] arena-cards.json parsed but held no ids')
    } catch (error) {
      // Never fail a draft over a corrupt correction file; the bundle's own
      // Scryfall-derived identity still works, just with the known defects.
      console.error('[ArenaCards] failed to read arena-cards.json:', error)
    }
  }
  cache.set(bundleRoot, table)
  return table
}

/** Test seam: drop the memoised table so a regenerated file is picked up. */
export function clearArenaCardsCache(): void {
  cache.clear()
}
